// <auto-generated />
namespace Knowledge_Management.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_tbl_solution_uploads : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_tbl_solution_uploads));
        
        string IMigrationMetadata.Id
        {
            get { return "201607270652478_add_tbl_solution_uploads"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
