// <auto-generated />
namespace Knowledge_Management.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_fie_description_column2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_fie_description_column2));
        
        string IMigrationMetadata.Id
        {
            get { return "201701020817121_add_fie_description_column2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
